[build]
rustflags = ["--cfg=web_sys_unstable_apis"]

[alias]
test-debug = "test --features debug"
clippy-debug = "clippy --fix --features debug --target wasm32-unknown-unknown"

# [patch."https://github.com/unyt-org/datex-core"]
# datex-core = { path = "../datex-core", default-features = false, features = [
#     "std",
#     "serde",
#     "wasm_logger",
#     "wasm_runtime",
#     "wasm_webrtc",
# ] }
